#!/usr/bin/env python

import sys

from march_rqt_training_log.training_log import TrainingLogPlugin
from rqt_gui.main import Main

plugin = 'march_rqt_training_log'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

