<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="march" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Switch between airgaiting or standing on the ground-->
    <!-- Value set to: 'world' fixes the robot to the world-->
    <!-- Value set to: 'base_link' makes the robot stand on the ground also set launch parameter fixed to false and set
    the hover_height to 0.0. Set ground_gait to true to ground gait in simulation.-->
    <xacro:arg name="ground_gait" default="false"/>

    <xacro:unless value="$(arg ground_gait)">
        <xacro:property name="parent_name" value="world"/>
        <xacro:property name="hover_height" value="0.3"/>
    </xacro:unless>
    <xacro:if value="$(arg ground_gait)">
        <xacro:property name="parent_name" value="base_link"/>
        <xacro:property name="hover_height" value="0.0"/>
        <gazebo>
            <plugin name="com_controller_plugin" filename="libmarch_gazebo_plugins.so"/>
        </gazebo>
    </xacro:if>

    <!-- The max effort of the rotary joints is lower then the value corresponding to 25A, because short-circuit errors
    have occured while applying the theoretical max effort for a long time. -->
    <xacro:arg name="max_effort_rotary" default="18000.0" />
    <xacro:arg name="max_effort_linear" default="22932.0" />  <!-- = 28 A -->
    <xacro:property name="max_effort_rotary" value="$(arg max_effort_rotary)" />
    <xacro:property name="max_effort_linear" value="$(arg max_effort_linear)" />

    <!-- Values for the safety limits, see https://wiki.ros.org/pr2_controller_manager/safety_limits -->
    <xacro:arg name="k_velocity_value_hfe" default="20000.0" />
    <xacro:arg name="k_velocity_value_kfe" default="20000.0" />
    <xacro:arg name="k_velocity_value_haa" default="20000.0" />
    <xacro:arg name="k_velocity_value_adpf" default="20000.0" />
    <xacro:property name="k_velocity_value_hfe" value="$(arg k_velocity_value_hfe)" />
    <xacro:property name="k_velocity_value_kfe" value="$(arg k_velocity_value_kfe)" />
    <xacro:property name="k_velocity_value_haa" value="$(arg k_velocity_value_haa)" />
    <xacro:property name="k_velocity_value_adpf" value="$(arg k_velocity_value_adpf)" />

    <xacro:arg name="k_position_value_hfe" default="14.88" />
    <xacro:arg name="k_position_value_kfe" default="14.88" />
    <xacro:arg name="k_position_value_haa" default="4.0" />
    <xacro:arg name="k_position_value_adpf" default="5.0" />
    <xacro:property name="k_position_value_hfe" value="$(arg k_position_value_hfe)" />
    <xacro:property name="k_position_value_kfe" value="$(arg k_position_value_kfe)" />
    <xacro:property name="k_position_value_haa" value="$(arg k_position_value_haa)" />
    <xacro:property name="k_position_value_adpf" value="$(arg k_position_value_adpf)" />

    <!-- Constants for robot dimensions -->
    <!-- Masses determined in Catia, see https://confluence.projectmarch.nl:8443/display/51/URDF+description -->
    <xacro:property name="width" value="0.05"/> <!-- Square dimensions (widthxwidth) of beams -->

    <xacro:property name="hip_base_height" value="0.160"/>
    <xacro:property name="hip_base_mass" value="8.686"/>
    <!-- mass = Hip base + HAA actuators -->

    <xacro:property name="hip_aa_frame_height" value="0.170"/>
    <xacro:property name="hip_aa_frame_width" value="0.1395"/>
    <xacro:property name="hip_aa_mass" value="2.982"/>
    <!-- mass = Moving hip -->

    <xacro:property name="upper_leg_height" value="0.385"/>
    <xacro:property name="upper_leg_offset" value="0.04"/>
    <xacro:property name="upper_leg_mass" value="4.995"/>
    <!-- mass = KFE joint + HFE joint + Upper leg -->

    <xacro:property name="lower_leg_height" value="0.385"/>
    <xacro:property name="lower_leg_mass" value="4.458"/>
    <!-- mass = Ankle actuator + Lower leg -->

    <xacro:property name="ankle_plate_height" value="0.12"/>
    <xacro:property name="ankle_plate_offset" value="0.07"/>

    <xacro:property name="foot_height_forward" value="${0.184}"/>
    <xacro:property name="foot_height_backward" value="${0.059}"/>
    <xacro:property name="foot_mass" value="1.821"/>
    <xacro:property name="foot_mu1" value="1"/>
    <xacro:property name="foot_mu2" value="1"/>
    <!-- Minimum allowable depth before contact correction impulse is applied. -->
    <xacro:property name="foot_min_depth" value="0.0005"/>
    <!-- mass = Passive ankle + foot -->

    <!-- Center of Mass (CoM) of the parts -->
    <!-- CoM has been determined in Catia, see https://confluence.projectmarch.nl:8443/display/51/URDF+description -->
    <!-- The Catia locations were defined in a global coordinate system with the origin at the center of the
         rotation axis of the two HFE joints. Here, the joints were all set at zero degrees. Hence, we need some
         translations to transfer it to the reference frame of each of the parts. Note that in the Catia x axis is
         the URDF y axis and the Catia y axis is the negative URDF x axis. The given CoM are for the right leg,
         the y coordinate will be inverted for the left leg. -->
    <xacro:property name="hip_base_com_x" value="${-hip_aa_frame_width + 0.147989}"/>
    <xacro:property name="hip_base_com_y" value="0.016341"/>
    <xacro:property name="hip_base_com_z" value="0.147761"/>

    <xacro:property name="hip_aa_com_x" value="${-hip_aa_frame_width + 0.108094}"/>
    <xacro:property name="hip_aa_com_y" value="${-hip_base_height/2 - hip_aa_frame_height + 0.197758}"/>
    <xacro:property name="hip_aa_com_z" value="0.029507"/>

    <xacro:property name="upper_leg_com_x" value="0.000709"/>
    <xacro:property name="upper_leg_com_y" value="${-hip_base_height/2 - hip_aa_frame_height +
                                                    upper_leg_offset + 0.215254}"/>
    <xacro:property name="upper_leg_com_z" value="-0.19205"/>

    <xacro:property name="lower_leg_com_x" value="-0.00321"/>
    <xacro:property name="lower_leg_com_y" value="${-hip_base_height/2 - hip_aa_frame_height +
                                                    upper_leg_offset + 0.184081}"/>
    <xacro:property name="lower_leg_com_z" value="${upper_leg_height - 0.527082}"/>

    <xacro:property name="foot_com_x" value="-0.028926"/>
    <xacro:property name="foot_com_y" value="${-hip_base_height/2 - hip_aa_frame_height +
                                               upper_leg_offset + ankle_plate_offset + 0.155916}"/>
    <xacro:property name="foot_com_z" value="${upper_leg_height + lower_leg_height + ankle_plate_height - 0.789788}"/>
    <xacro:property name="foot_scale" value="1.35"/>

    <!-- Inertia of the parts -->
    <!-- Inertia's have been determined in Catia, see
         https://confluence.projectmarch.nl:8443/display/51/URDF+description -->
    <!-- The inertia's were defined around the CoM. Note that in the Catia x axis is the URDF y axis and the Catia y
         axis is the negative URDF x axis, see confluence for the impact. The given inertia's are for the right leg,
         Ixy and Iyz will be inverted for the left leg. -->
    <xacro:property name="hip_base_Ixx" value="0.141"/>
    <xacro:property name="hip_base_Ixy" value="0.0000336"/>
    <xacro:property name="hip_base_Ixz" value="-0.007"/>
    <xacro:property name="hip_base_Iyy" value="0.087"/>
    <xacro:property name="hip_base_Iyz" value="0.0005089"/>
    <xacro:property name="hip_base_Izz" value="0.091"/>

    <xacro:property name="hip_aa_Ixx" value="0.013"/>
    <xacro:property name="hip_aa_Ixy" value="0.008"/>
    <xacro:property name="hip_aa_Ixz" value="0.005"/>
    <xacro:property name="hip_aa_Iyy" value="0.023"/>
    <xacro:property name="hip_aa_Iyz" value="-0.001"/>
    <xacro:property name="hip_aa_Izz" value="0.028"/>

    <xacro:property name="upper_leg_Ixx" value="0.127"/>
    <xacro:property name="upper_leg_Ixy" value="0.0001291"/>
    <xacro:property name="upper_leg_Ixz" value="-0.0002056"/>
    <xacro:property name="upper_leg_Iyy" value="0.122"/>
    <xacro:property name="upper_leg_Iyz" value="0.016"/>
    <xacro:property name="upper_leg_Izz" value="0.015"/>

    <xacro:property name="lower_leg_Ixx" value="0.075"/>
    <xacro:property name="lower_leg_Ixy" value="-0.027"/>
    <xacro:property name="lower_leg_Ixz" value="-0.008"/>
    <xacro:property name="lower_leg_Iyy" value="0.11"/>
    <xacro:property name="lower_leg_Iyz" value="-0.002"/>
    <xacro:property name="lower_leg_Izz" value="0.071" />

    <xacro:property name="foot_Ixx" value="0.021"/>
    <xacro:property name="foot_Ixy" value="-0.002"/>
    <xacro:property name="foot_Ixz" value="0.02"/>
    <xacro:property name="foot_Iyy" value="0.027"/>
    <xacro:property name="foot_Iyz" value="0.004"/>
    <xacro:property name="foot_Izz" value="0.01" />


    <!-- Joint properties -->
    <!-- For limit calculations, see https://confluence.projectmarch.nl:8443/pages/viewpage.action?pageId=268697604 -->
    <xacro:property name="left_hip_fe_rotation_lower_limit" value="${-21.04431152*pi/180}"/> <!-- rad -->
    <xacro:property name="left_hip_fe_rotation_upper_limit" value="${98.97033691*pi/180}"/> <!-- rad -->

    <xacro:property name="right_hip_fe_rotation_lower_limit" value="${-20.23406982*pi/180}"/> <!-- rad -->
    <xacro:property name="right_hip_fe_rotation_upper_limit" value="${99.48120117*pi/180}"/> <!-- rad -->

    <xacro:property name="hip_fe_soft_buffer" value="${3*pi/180}"/> <!-- rad -->
    <xacro:property name="hip_fe_effort_limit" value="${max_effort_rotary}"/> <!-- IU -->
    <xacro:property name="hip_fe_velocity_limit" value="2.0"/> <!-- rad/s -->

    <xacro:property name="left_hip_aa_rotation_lower_limit" value="${-18.54492188*pi/180}"/> <!-- rad -->
    <xacro:property name="left_hip_aa_rotation_upper_limit" value="${16.34765625*pi/180}"/> <!-- rad -->

    <xacro:property name="right_hip_aa_rotation_lower_limit" value="${-18.10546875*pi/180}"/> <!-- rad -->
    <xacro:property name="right_hip_aa_rotation_upper_limit" value="${15.99609375*pi/180}"/> <!-- rad -->

    <xacro:property name="hip_aa_soft_buffer" value="${3.5*pi/180}"/> <!-- rad -->
    <xacro:property name="hip_aa_effort_limit" value="${max_effort_linear}"/> <!-- IU -->
    <xacro:property name="hip_aa_velocity_limit" value="1.0"/> <!-- rad/s -->

    <xacro:property name="left_knee_rotation_lower_limit" value="${-5.012512207*pi/180}"/>
    <xacro:property name="left_knee_rotation_upper_limit" value="${112.4230957*pi/180}"/>

    <xacro:property name="right_knee_rotation_lower_limit" value="${-4.89440918*pi/180}"/>
    <xacro:property name="right_knee_rotation_upper_limit" value="${115.3097534*pi/180}"/>

    <xacro:property name="knee_extension_soft_buffer" value="${3.5*pi/180}"/> <!-- rad -->
    <xacro:property name="knee_flexion_soft_buffer" value="${3*pi/180}"/> <!-- rad -->
    <xacro:property name="knee_effort_limit" value="${max_effort_rotary}"/> <!-- IU -->
    <xacro:property name="knee_velocity_limit" value="2.5"/>

    <xacro:property name="left_ankle_rotation_lower_limit" value="${-30.30401611*pi/180}"/>
    <xacro:property name="left_ankle_rotation_upper_limit" value="${11.88348389*pi/180}"/>

    <xacro:property name="right_ankle_rotation_lower_limit" value="${-27.203125*pi/180}"/>
    <xacro:property name="right_ankle_rotation_upper_limit" value="${10.23828125*pi/180}"/>

    <xacro:property name="ankle_dorsalflexion_soft_buffer" value="${5*pi/180}"/> <!-- rad -->
    <xacro:property name="ankle_plantarflexion_soft_buffer" value="${3*pi/180}"/> <!-- rad -->
    <xacro:property name="ankle_effort_limit" value="${max_effort_linear}"/> <!-- IU -->
    <xacro:property name="ankle_velocity_limit" value="1.0"/>



    <xacro:property name="camera_link" value="0.05"/> <!-- Size of square 'camera' box -->
    <xacro:property name="axel_offset" value="0.05"/> <!-- Space btw top of beam and the each joint -->

    <!-- Import all Gazebo-customization elements, including Gazebo colors -->
    <xacro:include filename="$(find march_description)/urdf/march.gazebo"/>

    <material name="blue">
        <color rgba="0 0 0.6 1"/>
    </material>

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="${parent_name}"/>


    <!-- Parts -->
    <!-- Hip-->
    <link name="hip_base">
        <visual>
            <origin xyz="${-hip_aa_frame_width} 0 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/HipBase.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <origin xyz="${hip_base_com_x} ${hip_base_com_y} ${hip_base_com_z}" rpy="0 0 0"/>
            <mass value="${hip_base_mass}"/>
            <inertia
                    ixx="${hip_base_Ixx}"
                    ixy="${hip_base_Ixy}"
                    ixz="${hip_base_Ixz}"
                    iyy="${hip_base_Iyy}"
                    iyz="${hip_base_Iyz}"
                    izz="${hip_base_Izz}" />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${hip_base_height} ${width}"/>
            </geometry>
        </collision>
    </link>

    <!-- IMU-->
    <link name="imu_link">
    </link>

    <!-- Left Moving Hip-->
    <link name="hip_aa_frame_left_side">
        <visual>
            <origin xyz="${-hip_aa_frame_width} ${hip_base_height/2} 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/LeftHAA.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 ${-hip_aa_frame_height/2} 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${hip_aa_frame_height} ${width}"/>
            </geometry>
        </collision>
    </link>

    <link name="hip_aa_frame_left_front">
        <inertial>
            <origin xyz="${hip_aa_com_x} ${-hip_aa_com_y} ${hip_aa_com_z}" rpy="0 0 0"/>
            <mass value="${hip_aa_mass}"/>
            <inertia
                    ixx="${hip_aa_Ixx}"
                    ixy="${-hip_aa_Ixy}"
                    ixz="${hip_aa_Ixz}"
                    iyy="${hip_aa_Iyy}"
                    iyz="${-hip_aa_Iyz}"
                    izz="${hip_aa_Izz}" />
        </inertial>

        <collision>
            <origin xyz="${-hip_aa_frame_width/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${hip_aa_frame_width} ${width} ${width}"/>
            </geometry>
        </collision>
    </link>

    <!-- Upper Leg Left-->
    <link name="upper_leg_left">
        <visual>
            <origin xyz="0 ${hip_base_height/2 + hip_aa_frame_height - upper_leg_offset} 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/UpperLeftLeg.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <origin xyz="${upper_leg_com_x} ${-upper_leg_com_y} ${upper_leg_com_z}" rpy="0 0 0"/>
            <mass value="${upper_leg_mass}"/>
            <inertia
                    ixx="${upper_leg_Ixx}"
                    ixy="${-upper_leg_Ixy}"
                    ixz="${upper_leg_Ixz}"
                    iyy="${upper_leg_Iyy}"
                    iyz="${-upper_leg_Iyz}"
                    izz="${upper_leg_Izz}" />
        </inertial>

        <collision>
            <origin xyz="0 0 ${-upper_leg_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${upper_leg_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Lower Leg Left -->
    <link name="lower_leg_left">
        <visual>
            <origin
                xyz="0 ${hip_base_height/2 + hip_aa_frame_height - upper_leg_offset} ${upper_leg_height}"
                rpy="0 0 ${pi}"
            />
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/LowerLeftLeg.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <origin xyz="${lower_leg_com_x} ${-lower_leg_com_y} ${lower_leg_com_z}" rpy="0 0 0"/>
            <mass value="${lower_leg_mass}"/>
            <inertia
                    ixx="${lower_leg_Ixx}"
                    ixy="${-lower_leg_Ixy}"
                    ixz="${lower_leg_Ixz}"
                    iyy="${lower_leg_Iyy}"
                    iyz="${-lower_leg_Iyz}"
                    izz="${lower_leg_Izz}" />
        </inertial>

        <collision>
            <origin xyz="0 0 ${-lower_leg_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${lower_leg_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Ankle plate Left -->
    <link name="ankle_plate_left">
        <visual>
            <origin
                xyz="0
                     ${hip_base_height/2 + hip_aa_frame_height - upper_leg_offset - ankle_plate_offset}
                     ${foot_scale * (upper_leg_height + lower_leg_height)}"
                rpy="0 0 ${pi}"
            />
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/LeftFoot.stl" scale="1 1 ${foot_scale}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${-ankle_plate_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${ankle_plate_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Foot Left -->
    <link name="foot_left">
        <inertial>
            <origin xyz="${foot_com_x} ${-foot_com_y} ${foot_com_z}" rpy="0 0 0"/>
            <mass value="${foot_mass}"/>
            <inertia
                    ixx="${foot_Ixx}"
                    ixy="${-foot_Ixy}"
                    ixz="${foot_Ixz}"
                    iyy="${foot_Iyy}"
                    iyz="${-foot_Iyz}"
                    izz="${foot_Izz}" />
        </inertial>
        <collision>
            <origin xyz="${(-foot_height_forward+foot_height_backward)/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${foot_height_forward+foot_height_backward} ${width} ${width}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="foot_left">
        <mu1>${foot_mu1}</mu1>
        <mu2>${foot_mu2}</mu2>
        <minDepth>${foot_min_depth}</minDepth>
        <fdir1>1 0 0</fdir1>
    </gazebo>

    <!-- Right Moving Hip-->
    <link name="hip_aa_frame_right_side">
        <visual>
            <origin xyz="${-hip_aa_frame_width} ${-hip_base_height/2} 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/RightHAA.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 ${hip_aa_frame_height/2} 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${hip_aa_frame_height} ${width}"/>
            </geometry>
        </collision>
    </link>

    <link name="hip_aa_frame_right_front">
        <inertial>
            <origin xyz="${hip_aa_com_x} ${hip_aa_com_y} ${hip_aa_com_z}" rpy="0 0 0"/>
            <mass value="${hip_aa_mass}"/>
            <inertia
                    ixx="${hip_aa_Ixx}"
                    ixy="${hip_aa_Ixy}"
                    ixz="${hip_aa_Ixz}"
                    iyy="${hip_aa_Iyy}"
                    iyz="${hip_aa_Iyz}"
                    izz="${hip_aa_Izz}" />
        </inertial>

        <collision>
            <origin xyz="${-hip_aa_frame_width/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${hip_aa_frame_width} ${width} ${width}"/>
            </geometry>
        </collision>
    </link>

    <!-- Upper Leg Right-->
    <link name="upper_leg_right">
        <visual>
            <origin xyz="0 ${-hip_base_height/2 - hip_aa_frame_height + upper_leg_offset} 0" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/UpperRightLeg.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <origin xyz="${upper_leg_com_x} ${upper_leg_com_y} ${upper_leg_com_z}" rpy="0 0 0"/>
            <mass value="${upper_leg_mass}"/>
            <inertia
                    ixx="${upper_leg_Ixx}"
                    ixy="${upper_leg_Ixy}"
                    ixz="${upper_leg_Ixz}"
                    iyy="${upper_leg_Iyy}"
                    iyz="${upper_leg_Iyz}"
                    izz="${upper_leg_Izz}" />
        </inertial>

        <collision>
            <origin xyz="0 0 ${-upper_leg_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${upper_leg_height}"/>
            </geometry>
        </collision>

    </link>

    <!-- Lower Leg Right -->
    <link name="lower_leg_right">
        <visual>
            <origin
                xyz="0 ${-hip_base_height/2 - hip_aa_frame_height + upper_leg_offset} ${upper_leg_height}"
                rpy="0 0 ${pi}"
            />
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/LowerRightLeg.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <origin xyz="${lower_leg_com_x} ${lower_leg_com_y} ${lower_leg_com_z}" rpy="0 0 0"/>
            <mass value="${lower_leg_mass}"/>
            <inertia
                    ixx="${lower_leg_Ixx}"
                    ixy="${lower_leg_Ixy}"
                    ixz="${lower_leg_Ixz}"
                    iyy="${lower_leg_Iyy}"
                    iyz="${lower_leg_Iyz}"
                    izz="${lower_leg_Izz}" />
        </inertial>

        <collision>
            <origin xyz="0 0 ${-lower_leg_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${lower_leg_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Ankle Plate Right -->
    <link name="ankle_plate_right">
        <visual>
            <origin
                xyz="0
                    ${-hip_base_height/2 - hip_aa_frame_height+ upper_leg_offset + ankle_plate_offset}
                    ${foot_scale * (upper_leg_height + lower_leg_height)}"
                rpy="0 0 ${pi}"/>
            />
            <geometry>
                <mesh filename="package://march_description/urdf/stl-files/RightFoot.stl" scale="1 1 ${foot_scale}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${-ankle_plate_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${ankle_plate_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Foot Right -->
    <link name="foot_right">
        <inertial>
            <origin xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}" rpy="0 0 0"/>
            <mass value="${foot_mass}"/>
            <inertia
                    ixx="${foot_Ixx}"
                    ixy="${foot_Ixy}"
                    ixz="${foot_Ixz}"
                    iyy="${foot_Iyy}"
                    iyz="${foot_Iyz}"
                    izz="${foot_Izz}" />
        </inertial>
        <collision>
            <origin xyz="${(-foot_height_forward+foot_height_backward)/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${foot_height_forward+foot_height_backward} ${width} ${width}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="foot_right">
        <mu1>${foot_mu1}</mu1>
        <mu2>${foot_mu2}</mu2>
        <minDepth>${foot_min_depth}</minDepth>
        <fdir1>1 0 0</fdir1>
    </gazebo>

    <!-- Joints -->
    <joint name="imu_joint" type="fixed">
        <parent link="${parent_name}"/>
        <child link="imu_link"/>
    </joint>

    <joint name="hip" type="fixed">
        <parent link="imu_link"/>
        <child link="hip_base"/>
        <origin xyz="0 0 ${lower_leg_height+upper_leg_height+ankle_plate_height+width/2.0+hover_height}" rpy="0 0 0"/>
    </joint>

    <joint name="left_hip_aa" type="revolute">
        <parent link="hip_base"/>
        <child link="hip_aa_frame_left_side"/>
        <origin xyz="0 ${-hip_base_height/2} 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${hip_aa_velocity_limit}"
               effort="${hip_aa_effort_limit}"
               lower="${left_hip_aa_rotation_lower_limit}"
               upper="${left_hip_aa_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${left_hip_aa_rotation_lower_limit + hip_aa_soft_buffer}"
                           soft_upper_limit="${left_hip_aa_rotation_upper_limit - hip_aa_soft_buffer}"
                           k_position="${k_position_value_haa}"
                           k_velocity="${k_velocity_value_haa}" />
    </joint>

    <joint name="left_hip_angle" type="fixed">
        <parent link="hip_aa_frame_left_side"/>
        <child link="hip_aa_frame_left_front"/>
        <origin xyz="0 ${-hip_aa_frame_height} 0" rpy="0 0 0"/>
    </joint>

    <joint name="left_hip_fe" type="revolute">
        <parent link="hip_aa_frame_left_front"/>
        <child link="upper_leg_left"/>
        <origin xyz="${-hip_aa_frame_width} ${upper_leg_offset} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${hip_fe_velocity_limit}"
               effort="${hip_fe_effort_limit}"
               lower="${left_hip_fe_rotation_lower_limit}"
               upper="${left_hip_fe_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${left_hip_fe_rotation_lower_limit + hip_fe_soft_buffer}"
                           soft_upper_limit="${left_hip_fe_rotation_upper_limit - hip_fe_soft_buffer}"
                           k_position="${k_position_value_hfe}"
                           k_velocity="${k_velocity_value_hfe}" />
    </joint>

    <joint name="left_knee" type="revolute">
        <parent link= "upper_leg_left"/>
        <child link="lower_leg_left"/>
        <origin xyz="0 0 ${-upper_leg_height}" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>

        <limit velocity="${knee_velocity_limit}"
               effort="${knee_effort_limit}"
               lower="${left_knee_rotation_lower_limit}"
               upper="${left_knee_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${left_knee_rotation_lower_limit + knee_extension_soft_buffer}"
                           soft_upper_limit="${left_knee_rotation_upper_limit - knee_flexion_soft_buffer}"
                           k_position="${k_position_value_kfe}"
                           k_velocity="${k_velocity_value_kfe}" />
    </joint>

    <joint name="left_ankle" type="revolute">
        <parent link="lower_leg_left"/>
        <child link="ankle_plate_left"/>
        <origin xyz="0 ${ankle_plate_offset} ${-lower_leg_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${ankle_velocity_limit}"
               effort="${ankle_effort_limit}"
               lower="${left_ankle_rotation_lower_limit}"
               upper="${left_ankle_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${left_ankle_rotation_lower_limit + ankle_plantarflexion_soft_buffer}"
                           soft_upper_limit="${left_ankle_rotation_upper_limit - ankle_dorsalflexion_soft_buffer}"
                           k_position="${k_position_value_adpf}"
                           k_velocity="${k_velocity_value_adpf}" />
    </joint>

    <joint name="left_foot_angle" type="fixed">
        <parent link="ankle_plate_left"/>
        <child link="foot_left"/>
        <origin xyz="0 0 ${-ankle_plate_height}" rpy="0 0 0"/>
    </joint>

    <joint name="right_hip_aa" type="revolute">
        <parent link="hip_base"/>
        <child link="hip_aa_frame_right_side"/>
        <origin xyz="0 ${hip_base_height/2} 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>

        <limit velocity="${hip_aa_velocity_limit}"
               effort="${hip_aa_effort_limit}"
               lower="${right_hip_aa_rotation_lower_limit}"
               upper="${right_hip_aa_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${right_hip_aa_rotation_lower_limit + hip_aa_soft_buffer}"
                           soft_upper_limit="${right_hip_aa_rotation_upper_limit - hip_aa_soft_buffer}"
                           k_position="${k_position_value_haa}"
                           k_velocity="${k_velocity_value_haa}" />

    </joint>

    <joint name="right_hip_angle" type="fixed">
        <parent link="hip_aa_frame_right_side"/>
        <child link="hip_aa_frame_right_front"/>
        <origin xyz="0 ${hip_aa_frame_height} 0" rpy="0 0 0"/>
    </joint>

    <joint name="right_hip_fe" type="revolute">
        <parent link="hip_aa_frame_right_front"/>
        <child link="upper_leg_right"/>
        <origin xyz="${-hip_aa_frame_width} ${-upper_leg_offset} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${hip_fe_velocity_limit}"
               effort="${hip_fe_effort_limit}"
               lower="${right_hip_fe_rotation_lower_limit}"
               upper="${right_hip_fe_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${right_hip_fe_rotation_lower_limit + hip_fe_soft_buffer}"
                           soft_upper_limit="${right_hip_fe_rotation_upper_limit - hip_fe_soft_buffer}"
                           k_position="${k_position_value_hfe}"
                           k_velocity="${k_velocity_value_hfe}" />

    </joint>

    <joint name="right_knee" type="revolute">
        <parent link="upper_leg_right"/>
        <child link="lower_leg_right"/>
        <origin xyz="0 0 ${-upper_leg_height}" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>

        <limit velocity="${knee_velocity_limit}"
               effort="${knee_effort_limit}"
               lower="${right_knee_rotation_lower_limit}"
               upper="${right_knee_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${right_knee_rotation_lower_limit + knee_extension_soft_buffer}"
                           soft_upper_limit="${right_knee_rotation_upper_limit - knee_flexion_soft_buffer}"
                           k_position="${k_position_value_kfe}"
                           k_velocity="${k_velocity_value_kfe}" />
    </joint>

    <joint name="right_ankle" type="revolute">
        <parent link="lower_leg_right"/>
        <child link="ankle_plate_right"/>
        <origin xyz="0 ${-ankle_plate_offset} ${-lower_leg_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${ankle_velocity_limit}"
               effort="${ankle_effort_limit}"
               lower="${right_ankle_rotation_lower_limit}"
               upper="${right_ankle_rotation_upper_limit}"/>
        <safety_controller soft_lower_limit="${right_ankle_rotation_lower_limit + ankle_plantarflexion_soft_buffer}"
                           soft_upper_limit="${right_ankle_rotation_upper_limit - ankle_dorsalflexion_soft_buffer}"
                           k_position="${k_position_value_adpf}"
                           k_velocity="${k_velocity_value_adpf}" />
    </joint>

    <joint name="right_foot_angle" type="fixed">
        <parent link="ankle_plate_right"/>
        <child link="foot_right"/>
        <origin xyz="0 0 ${-ankle_plate_height}" rpy="0 0 0"/>
    </joint>



    <!-- ROS Control plugin for Gazebo -->
    <transmission name="left_hip_aa">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_hip_aa">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_hip_aa_motor">
            <mechanicalReduction>200</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_hip_fe">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_hip_fe">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_hip_fe_motor">
            <mechanicalReduction>101</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_knee">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_knee">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_knee_motor">
            <mechanicalReduction>101</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_ankle">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_ankle">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_ankle_motor">
            <mechanicalReduction>200</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="right_hip_aa">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_hip_aa">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_hip_aa_motor">
            <mechanicalReduction>200</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="right_hip_fe">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_hip_fe">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_hip_fe_motor">
            <mechanicalReduction>101</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="right_knee">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_knee">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_knee_motor">
            <mechanicalReduction>101</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="right_ankle">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_ankle">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_ankle_motor">
            <mechanicalReduction>200</mechanicalReduction>
        </actuator>
    </transmission>
</robot>
