#!/usr/bin/env python

import sys

from march_rqt_input_device.input_device import InputDevicePlugin
from rqt_gui.main import Main

plugin = 'rqt_input_device'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
